### ISSUE TITLE
OBJETO 3D_BLENDER

### ISSUE THREAD

**Issue by ElvisS10** [SistemasTecTlaxiaco/diseno-de-objeto-3d-en-blender-equipo-josue#2]
[Practica2.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-objeto-3d-en-blender-equipo-josue/files/6386576/Practica2.pdf)

**Comment by Karina-Vsqz** [comment]
**calificación:** 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
